// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockManager.Infrastructure.Persistence;

#nullable disable

namespace StockManager.Infrastructure.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20260114184251_AddSignedQuantityToStockMovements")]
    partial class AddSignedQuantityToStockMovements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("StockManager.Domain.Entities.PhoneModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Brand", "ModelName")
                        .IsUnique();

                    b.ToTable("phone_models", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Samsung",
                            ModelName = "A02"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Samsung",
                            ModelName = "A20"
                        });
                });

            modelBuilder.Entity("StockManager.Domain.Entities.Sku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CaseType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhoneModelId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("ProtectorType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhoneModelId");

                    b.ToTable("skus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CaseType = 2,
                            Category = 1,
                            Cost = 1500m,
                            Name = "Funda silicona Samsung A02",
                            PhoneModelId = 1,
                            Price = 3000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CaseType = 1,
                            Category = 1,
                            Cost = 1400m,
                            Name = "Funda transparente Samsung A20",
                            PhoneModelId = 2,
                            Price = 2800m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Category = 2,
                            Cost = 1200m,
                            Name = "Templado reforzado Samsung A02",
                            PhoneModelId = 1,
                            Price = 2500m,
                            ProtectorType = 2,
                            Stock = 12
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Category = 2,
                            Cost = 1800m,
                            Name = "Templado anti-espía Samsung A20",
                            PhoneModelId = 2,
                            Price = 3500m,
                            ProtectorType = 3,
                            Stock = 5
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Category = 3,
                            Cost = 4000m,
                            Name = "Cargador 20W USB-C",
                            Price = 7500m,
                            Stock = 6
                        });
                });

            modelBuilder.Entity("StockManager.Domain.Entities.StockMovement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("SignedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SkuId");

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("StockManager.Domain.Entities.Sku", b =>
                {
                    b.HasOne("StockManager.Domain.Entities.PhoneModel", "PhoneModel")
                        .WithMany()
                        .HasForeignKey("PhoneModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PhoneModel");
                });

            modelBuilder.Entity("StockManager.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("StockManager.Domain.Entities.Sku", "Sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sku");
                });
#pragma warning restore 612, 618
        }
    }
}
